require("config")
require("plugins/which-key")
require("keymaps")
require("base")
require("picker")
require("git")
require("debugger")
require("plugins/completions")
require("ai")
require("plugins/catppuccin")
require("plugins/mini-icons")
vim.api.nvim_create_autocmd("UIEnter", {
  once = true,
  callback = function()
    require("plugins/lsp")
  end,
})
require("plugins/mini-pairs")
require("plugins/formatter")
require("plugins/nvim-surround")
require("plugins/treesitter")
require("plugins/flash")
require("plugins/grug-far")
require("plugins/messages")
require("plugins/sql")
require("plugins/undotree")
require("plugins/illuminate")
require("plugins/urls")
require("rest")
require("ui")
